"""
Agent phases: perceive, plan, act, reflect.

Each phase is a pure function that takes structured input and
returns structured output. This makes the agent easy to test,
observe, and swap pieces of (e.g., plug in a real LLM for plan).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


# ---------- Data shapes ---------- #

@dataclass
class Perception:
    intent: str
    domain: str
    actions: list[str]
    confidence: int  # 0-100


@dataclass
class TestPlan:
    name: str
    steps: list[str]


@dataclass
class ExecutionResult:
    passed: bool
    failed_step: int | None = None
    error_type: str | None = None
    error_message: str | None = None


@dataclass
class Reflection:
    root_cause: str
    confidence: int
    repair_strategy: str
    repair_patch: str = ""


# ---------- Phase 1: Perceive ---------- #

DOMAIN_KEYWORDS = {
    "e-commerce / checkout": ["checkout", "cart", "payment", "purchase", "order"],
    "authentication": ["login", "sign in", "signin", "logout", "password"],
    "registration": ["signup", "sign up", "register", "account creation"],
    "search": ["search", "filter", "find", "query"],
    "admin": ["admin", "dashboard", "settings", "permissions"],
}


def perceive(intent: str) -> Perception:
    lower = intent.lower()
    detected_domain = "generic web app"
    confidence = 60
    for domain, keywords in DOMAIN_KEYWORDS.items():
        if any(kw in lower for kw in keywords):
            detected_domain = domain
            confidence = 91
            break

    actions = ["navigate"]
    if any(w in lower for w in ("fill", "enter", "type", "login", "sign", "checkout")):
        actions.append("fill form")
    if any(w in lower for w in ("click", "submit", "press", "place", "login", "checkout")):
        actions.append("submit")
    actions.append("verify")

    return Perception(intent=intent, domain=detected_domain, actions=actions, confidence=confidence)


# ---------- Phase 2: Plan ---------- #

PLAN_TEMPLATES: dict[str, list[str]] = {
    "e-commerce / checkout": [
        "Navigate to /cart",
        "Click 'Proceed to checkout'",
        "Fill shipping form",
        "Fill payment details",
        "Click 'Place order'",
        "Assert order confirmation",
    ],
    "authentication": [
        "Navigate to /login",
        "Fill email field",
        "Fill password field",
        "Click 'Sign in'",
        "Assert dashboard heading visible",
    ],
    "registration": [
        "Navigate to /signup",
        "Fill name fields",
        "Fill email and password",
        "Accept terms checkbox",
        "Click 'Create account'",
        "Assert verification email prompt",
    ],
    "search": [
        "Navigate to home",
        "Type query into search box",
        "Press Enter",
        "Assert results list visible",
    ],
}


def _slug(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_\s]", "", text.lower())
    return re.sub(r"\s+", "_", slug.strip())[:80] or "generated_test"


def plan(perception: Perception) -> TestPlan:
    steps = PLAN_TEMPLATES.get(
        perception.domain,
        [
            "Navigate to the application",
            "Trigger the primary action",
            "Assert expected outcome",
        ],
    )
    return TestPlan(name=_slug(perception.intent), steps=list(steps))


# ---------- Phase 3: Act (code generation) ---------- #

def generate_test_code(test_plan: TestPlan, intent: str, repaired: bool = False) -> str:
    """Render a Playwright test from the plan."""
    repair_comment = "# Auto-repaired: added explicit enabled-state wait\n    " if repaired else ""
    steps_code = "\n    ".join(
        f"# Step {i}: {step}\n    page.wait_for_load_state('networkidle')"
        for i, step in enumerate(test_plan.steps, start=1)
    )
    return f'''"""
Generated by Autonomous Playwright Agent.
Intent: {intent}
"""
from playwright.sync_api import Page, expect


def test_{test_plan.name}(page: Page) -> None:
    {repair_comment}page.goto("https://example.com")

    {steps_code}

    expect(page).to_have_title(lambda t: len(t) > 0)
'''


# ---------- Phase 4: Reflect ---------- #

REFLECTION_RULES = {
    "ELEMENT_DISABLED": Reflection(
        root_cause="Target element rendered but disabled at click time.",
        confidence=92,
        repair_strategy="Add explicit toBeEnabled() wait before click",
        repair_patch="await expect(locator).toBeEnabled({ timeout: 10000 });",
    ),
    "ELEMENT_NOT_VISIBLE": Reflection(
        root_cause="Element present in DOM but not visible.",
        confidence=88,
        repair_strategy="Scroll into view and wait for visibility",
        repair_patch="await locator.scrollIntoViewIfNeeded(); await expect(locator).toBeVisible();",
    ),
    "TIMEOUT": Reflection(
        root_cause="Action did not complete within the default timeout.",
        confidence=75,
        repair_strategy="Increase timeout and add intermediate state assertion",
    ),
}


def reflect(result: ExecutionResult) -> Reflection:
    if result.passed or result.error_type is None:
        return Reflection(root_cause="N/A — test passed", confidence=100, repair_strategy="None")
    return REFLECTION_RULES.get(
        result.error_type,
        Reflection(
            root_cause=f"Unknown failure: {result.error_message}",
            confidence=40,
            repair_strategy="Escalate to human reviewer",
        ),
    )
