"""
AI Failure Analyzer CLI.

Reads a Playwright/CI failure log and produces a structured root-cause
report. Default output is a human-readable terminal report.

Supports --format json and --format jira for downstream automation.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

from patterns import Analysis, classify


def _render_text(a: Analysis) -> str:
    lines: list[str] = []
    lines.append("🔍 AI Failure Analysis Report")
    lines.append("═" * 60)
    lines.append(f"Test:           {a.test_location}")
    lines.append(f"Failure Type:   {a.failure_type}")
    lines.append(f"Severity:       {a.severity}")
    lines.append(f"Confidence:     {a.confidence}%")
    lines.append("")
    lines.append("Root Cause:")
    for line in a.root_cause.split(". "):
        if line:
            lines.append(f"  {line.strip().rstrip('.')}.")
    lines.append("")
    lines.append("Likely Causes (ranked):")
    for idx, (sev, desc) in enumerate(a.likely_causes, start=1):
        lines.append(f"  {idx}. [{sev:<8}] {desc}")
    lines.append("")
    lines.append("Suggested Fix:")
    lines.append(f"  • {a.suggested_fix}")
    if a.fix_snippet:
        lines.append("")
        lines.append("Fix Snippet:")
        for snippet_line in a.fix_snippet.split("\n"):
            lines.append(f"      {snippet_line}")
    lines.append("")
    return "\n".join(lines)


def _render_json(a: Analysis) -> str:
    return json.dumps(asdict(a), indent=2)


def _render_jira(a: Analysis) -> str:
    causes_md = "\n".join(
        f"- **[{sev}]** {desc}" for sev, desc in a.likely_causes
    )
    snippet_md = f"\n```\n{a.fix_snippet}\n```\n" if a.fix_snippet else ""
    return f"""## [{a.severity}] {a.failure_type} — {a.test_location}

**Auto-generated by AI Failure Analyzer** (confidence: {a.confidence}%)

### Root Cause
{a.root_cause}

### Likely Causes (ranked)
{causes_md}

### Suggested Fix
{a.suggested_fix}
{snippet_md}
### Triage Checklist
- [ ] Reproduce locally
- [ ] Verify suggested fix
- [ ] Update test or production code
- [ ] Re-run CI
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze CI test failure logs.")
    parser.add_argument("log_path", type=Path, help="Path to the failure log file")
    parser.add_argument(
        "--format",
        choices=("text", "json", "jira"),
        default="text",
        help="Output format (default: text)",
    )
    args = parser.parse_args()

    if not args.log_path.exists():
        print(f"❌ Log file not found: {args.log_path}", file=sys.stderr)
        return 1

    log_content = args.log_path.read_text()
    analysis = classify(log_content)

    if args.format == "json":
        print(_render_json(analysis))
    elif args.format == "jira":
        print(_render_jira(analysis))
    else:
        print(_render_text(analysis))

    return 0


if __name__ == "__main__":
    sys.exit(main())
